<a href="https://colab.research.google.com/github/AndrewHerrada/Timetabling/blob/main/Tablas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

## LOGIN TABLA MATERIA - DETALLE_MATERIA

In [3]:
# Rutas relativas a los archivos dentro de la carpeta "db"
ruta_archivo1 = "db/tablas_procesadas/Materia.xlsx"  
ruta_archivo2 = "db/tablas_procesadas/Detalle_materia.xlsx"

In [4]:
df_materias = pd.read_excel(ruta_archivo1, engine='openpyxl')
df_detalle_materia = pd.read_excel(ruta_archivo2, engine='openpyxl')

In [5]:
# Realizar el merge (login) usando "materia_id" como clave
df_merged = pd.merge(
    df_materias,         # Tabla izquierda (materias)
    df_detalle_materia, # Detalle solo de las regulares
    on="id_materia",     # Columna común
    how="inner"          # Tipo de join (inner para datos que coincidan en ambas tablas)
)

In [6]:
df_merged

,id_materia,nombre_materia,horas_semanales_tipicas,tipo_materia,laboratorio,clase_seguida,aula_req,curso,grupos
0,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A)
1,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (B),1°Inf (B)
2,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (A),1°Inf (A)
3,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (B),1°Inf (B)
4,CA-IC-001,Creatividad Artistica,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A)
...,...,...,...,...,...,...,...,...,...
120,OAG,Orquesta A (General),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv"
121,OAS,Orquesta A (Seccional),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv"
122,OBG,Orquesta B (General),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int"
123,OBS,Orquesta B (Seccional),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int"
124,OS,Orquesta Sinfonica,2,Conjunto,False,True,E-101,Conjunto4,"1°Int, 2°Int, 3°Int"

In [7]:
print("Filas en df_merged:", len(df_merged))

Filas en df_merged: 125

No hay existencia de filas duplicadas

In [8]:
print(df_merged.isnull().sum())

id_materia                  0
nombre_materia              0
horas_semanales_tipicas     0
tipo_materia                0
laboratorio                 0
clase_seguida               0
aula_req                   94
curso                       0
grupos                      0
dtype: int64

Existen 94 valores nulos, es correcto.

## LOGIN TABLA CURSO (STUDENS_GROUP)

In [9]:
ruta_archivo3 = "db/tablas_procesadas/Curso.xlsx"
df_curso = pd.read_excel(ruta_archivo3, engine='openpyxl')

In [10]:
df_merged = pd.merge(
    df_merged,                  # DataFrame con toda la información previa
    df_curso,        # Nueva tabla de horarios de cursos
    on="curso",             # Columna común
    how="left"                 # Mantener todos los registros de df_final
)

In [11]:
df_merged

,id_materia,nombre_materia,horas_semanales_tipicas,tipo_materia,laboratorio,clase_seguida,aula_req,curso,grupos,id_curso,detalle,nivel,inscritos,pos_curso
0,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0
1,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (B),1°Inf (B),G2,1°Infantil (B),Infantil,15.0,1.0
2,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0
3,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (B),1°Inf (B),G2,1°Infantil (B),Infantil,15.0,1.0
4,CA-IC-001,Creatividad Artistica,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,OAG,Orquesta A (General),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv",NaN,NaN,NaN,NaN,NaN
121,OAS,Orquesta A (Seccional),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv",NaN,NaN,NaN,NaN,NaN
122,OBG,Orquesta B (General),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN
123,OBS,Orquesta B (Seccional),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN
124,OS,Orquesta Sinfonica,2,Conjunto,False,True,E-101,Conjunto4,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN

Los valores nulos se deben llenar manualmente

## LOGIN TABLA PROFESOR_MATERIA

In [12]:
ruta_archivo4 = "db/tablas_procesadas/Profesor_materia.xlsx"
df_profesor_materia = pd.read_excel(ruta_archivo4, engine='openpyxl')

In [13]:
df_merged = pd.merge(
    df_merged,                  # DataFrame con toda la información previa
    df_profesor_materia,        # Nueva tabla de profesor asociado a su materia
    on=["id_materia", "curso"],             # Columna común
    how="left"                 # Mantener todos los registros de df_final
)

In [14]:
df_merged

,id_materia,nombre_materia,horas_semanales_tipicas,tipo_materia,laboratorio,clase_seguida,aula_req,curso,grupos,id_curso,detalle,nivel,inscritos,pos_curso,id_profesor
0,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0,P4
1,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (B),1°Inf (B),G2,1°Infantil (B),Infantil,15.0,1.0,P4
2,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0,P25
3,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (B),1°Inf (B),G2,1°Infantil (B),Infantil,15.0,1.0,P23
4,CA-IC-001,Creatividad Artistica,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0,P26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,OAG,Orquesta A (General),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv",NaN,NaN,NaN,NaN,NaN,P29
121,OAS,Orquesta A (Seccional),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv",NaN,NaN,NaN,NaN,NaN,P29
122,OBG,Orquesta B (General),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN,P29
123,OBS,Orquesta B (Seccional),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN,P29
124,OS,Orquesta Sinfonica,2,Conjunto,False,True,E-101,Conjunto4,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN,P17

In [15]:
ruta_archivo5 = "db/tablas_procesadas/Profesor.xlsx"
df_profesor = pd.read_excel(ruta_archivo5, engine='openpyxl')

In [16]:
df_merged = pd.merge(
    df_merged,                  # DataFrame con toda la información previa
    df_profesor,        # Nueva tabla de profesor asociado a su materia
    on="id_profesor",             # Columna común
    how="left"                 # Mantener todos los registros de df_final
)

In [17]:
df_merged

,id_materia,nombre_materia,horas_semanales_tipicas,tipo_materia,laboratorio,clase_seguida,aula_req,curso,grupos,id_curso,detalle,nivel,inscritos,pos_curso,id_profesor,nombre,seccion,categoria,pos_prof
0,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0,P4,Cecilia Padilla,Piano,Item,3
1,CI-IC-001,Canto Infantil,2,Regular,False,False,NaN,1°Inf (B),1°Inf (B),G2,1°Infantil (B),Infantil,15.0,1.0,P4,Cecilia Padilla,Piano,Item,3
2,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0,P25,David Janco,Piano,Contrato,24
3,TC-IC-001,Teclado,2,Regular,False,False,F-101,1°Inf (B),1°Inf (B),G2,1°Infantil (B),Infantil,15.0,1.0,P23,Denise Avila,Percusion,Contrato,22
4,CA-IC-001,Creatividad Artistica,2,Regular,False,False,NaN,1°Inf (A),1°Inf (A),G1,1°Infantil (A),Infantil,15.0,0.0,P26,Libertad Aguilar,Cuerda,Contrato,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,OAG,Orquesta A (General),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv",NaN,NaN,NaN,NaN,NaN,P29,4-5 profesores,Todas,Variado,28
121,OAS,Orquesta A (Seccional),2,Conjunto,False,True,NaN,Conjunto2,"1°Bas, 2°Bas, 3°Bas, 2°Inv, 3°Inv",NaN,NaN,NaN,NaN,NaN,P29,4-5 profesores,Todas,Variado,28
122,OBG,Orquesta B (General),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN,P29,4-5 profesores,Todas,Variado,28
123,OBS,Orquesta B (Seccional),2,Conjunto,False,True,NaN,Conjunto3,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN,P29,4-5 profesores,Todas,Variado,28
124,OS,Orquesta Sinfonica,2,Conjunto,False,True,E-101,Conjunto4,"1°Int, 2°Int, 3°Int",NaN,NaN,NaN,NaN,NaN,P17,Augusto Guzman,Direccion,Item,16

In [ ]:
# Eliminar columnas no necesarias
df_merged = df_merged.drop(columns=["id_materia", "tipo_materia", "curso", "id_curso", "detalle", "nivel", "inscritos","id_profesor", "seccion", "categoria", "nombre", "grupos"])  

# Verificar las columnas restantes
print("Columnas finales:", df_merged.columns.tolist())

Columnas finales: ['nombre_materia', 'horas_semanales_tipicas', 'laboratorio', 'clase_seguida', 'aula_req', 'grupos', 'pos_curso', 'pos_prof']

In [20]:
columnas = [
    'nombre_materia', 
    'pos_prof', 
    'pos_curso', 
    'laboratorio', 
    'horas_semanales_tipicas',  
    'clase_seguida', 
    'aula_req'
]

# Reordenar el DataFrame
df_merged = df_merged[columnas]

In [22]:
df_merged

,nombre_materia,pos_prof,pos_curso,laboratorio,horas_semanales_tipicas,clase_seguida,aula_req
0,Canto Infantil,3,0.0,False,2,False,NaN
1,Canto Infantil,3,1.0,False,2,False,NaN
2,Teclado,24,0.0,False,2,False,F-101
3,Teclado,22,1.0,False,2,False,F-101
4,Creatividad Artistica,25,0.0,False,2,False,NaN
...,...,...,...,...,...,...,...
120,Orquesta A (General),28,NaN,False,2,True,NaN
121,Orquesta A (Seccional),28,NaN,False,2,True,NaN
122,Orquesta B (General),28,NaN,False,2,True,NaN
123,Orquesta B (Seccional),28,NaN,False,2,True,NaN
124,Orquesta Sinfonica,16,NaN,False,2,True,E-101

In [23]:
df_merged.insert(0, 'id_curso', ['C' + str(i + 1) for i in range(len(df_merged))])

df_merged

,id_curso,nombre_materia,pos_prof,pos_curso,laboratorio,horas_semanales_tipicas,clase_seguida,aula_req
0,C1,Canto Infantil,3,0.0,False,2,False,NaN
1,C2,Canto Infantil,3,1.0,False,2,False,NaN
2,C3,Teclado,24,0.0,False,2,False,F-101
3,C4,Teclado,22,1.0,False,2,False,F-101
4,C5,Creatividad Artistica,25,0.0,False,2,False,NaN
...,...,...,...,...,...,...,...,...
120,C121,Orquesta A (General),28,NaN,False,2,True,NaN
121,C122,Orquesta A (Seccional),28,NaN,False,2,True,NaN
122,C123,Orquesta B (General),28,NaN,False,2,True,NaN
123,C124,Orquesta B (Seccional),28,NaN,False,2,True,NaN
124,C125,Orquesta Sinfonica,16,NaN,False,2,True,E-101

In [ ]:
# Genera el archivo courses.txt
with open("courses.txt", "w") as file:
    for _, row in df_merged.iterrows():
        course_str = f'new Course("{row["id_curso"]}", "{row["nombre_materia"]}", professors[{row["pos_prof"]}]'
        
        # Agrega `pos_curso` si no es nulo
        if pd.notna(row["pos_curso"]):
            course_str += f', studentGroups[{int(row["pos_curso"])}]'
        else:
            course_str += ', null'  # O puedes omitirlo si prefieres
        
        course_str += f', {str(row["laboratorio"]).lower()}, {row["horas_semanales_tipicas"]}, {str(row["clase_seguida"]).lower()}'
        
        # Agrega el valor de `aula_req` si no es nulo
        if pd.notna(row["aula_req"]):
            course_str += f', "{row["aula_req"]}"'
        
        course_str += '),\n'
        
        # Escribe la línea en el archivo
        file.write(course_str)

print("Archivo courses.txt generado con éxito.")

Archivo courses.txt generado con éxito.

In [25]:
ruta = "db/tablas_procesadas/Curso.xlsx"
data_curso = pd.read_excel(ruta, engine='openpyxl')

In [26]:
with open("student_groups.txt", "w") as file:
    for _, row in data_curso.iterrows():
        group_str = f'new StudentGroup("{row["id_curso"]}", "{row["curso"]}", {row["inscritos"]}),\n'
        file.write(group_str)

print("Archivo student_groups.txt generado con éxito.")

Archivo student_groups.txt generado con éxito.

In [27]:
ruta2 = "db/tablas_procesadas/Profesor.xlsx"
data_profesor = pd.read_excel(ruta2, engine='openpyxl')

In [28]:
with open("professors.txt", "w") as file:
    for _, row in data_profesor.iterrows():
        # Construir la declaración de Professor
        professor_str = f'new Professor("{row["id_profesor"]}", "{row["nombre"]}"),\n'
        # Escribir en el archivo
        file.write(professor_str)

print("Archivo professors.txt generado con éxito.")

Archivo professors.txt generado con éxito.

In [29]:
ruta3 = "db/tablas_procesadas/Sala.xlsx"
data_sala = pd.read_excel(ruta3, engine='openpyxl')

In [30]:
with open("rooms.txt", "w") as file:
    for _, row in data_sala.iterrows():
        # Construir la declaración de Room
        room_str = f'new Room("{row["sala_id"]}", {row["capacidad"]}, {str(row["laboratorio"]).lower()}),\n'
        # Escribir en el archivo
        file.write(room_str)

print("Archivo rooms.txt generado con éxito.")

Archivo rooms.txt generado con éxito.